# Generated by Django 5.1.4 on 2024-12-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', 'student'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.PositiveIntegerField(default=1, verbose_name="To'lov oyi"),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(choices=[('MWF1', 'Mon-Wed-Fri-8-10'), ('MWF2', 'Mon-Wed-Fri-10-12'), ('MWF3', 'Mon-Wed-Fri-13-15'), ('MWF4', 'Mon-Wed-Fri-15-17'), ('TTS1', 'Tue-Thu-Sat-8-10'), ('TTS2', 'Tue-Thu-Sat-10-12'), ('TTS3', 'Tue-Thu-Sat-13-15'), ('TTS4', 'Tue-Thu-Sat-15-17'), ('6days1', 'Mon-Sat1'), ('6days2', 'Mon-Sat2'), ('6days3', 'Mon-Sat3'), ('6days4', 'Mon-Sat4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', "To'langan"), ('unpaid', "To'lanmagan")], default='unpaid', max_length=20),
        ),
    ]
