# Generated by Django 5.1.4 on 2024-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grade_options_remove_grade_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
