# Generated by Django 5.1.4 on 2025-01-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_monthperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.AddField(
            model_name='attendance',
            name='month_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.monthperiod'),
        ),
        migrations.AddField(
            model_name='grade',
            name='month_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.monthperiod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='month_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.monthperiod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('bank_transfer', "Pul o'tkazish"), ('card', 'Karta orqali'), ('payment_system', "To'lov tizimlari")], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(choices=[('MWF1', 'Dushanba-Chorshanba-Juma (8:00-10:00)'), ('MWF2', 'Dushanba-Chorshanba-Juma (10:00-12:00)'), ('MWF3', 'Dushanba-Chorshanba-Juma (13:30-15:30)'), ('MWF4', 'Dushanba-Chorshanba-Juma (15:30-17:30)'), ('TTS1', 'Seshanba-Payshanba-Shanba (8:00-10:00)'), ('TTS2', 'Seshanba-Payshanba-Shanba (10:00-12:00)'), ('TTS3', 'Seshanba-Payshanba-Shanba (13:30-15:30)'), ('TTS4', 'Seshanba-Payshanba-Shanba (15:30-17:30)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('month_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.monthperiod')),
            ],
        ),
    ]
