# Generated by Django 5.1.4 on 2025-02-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_grade_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_per_month',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student'), ('applicant', 'Applicant')], default='applicant', max_length=10),
        ),
    ]
