# Generated by Django 5.1.4 on 2025-02-24 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_price_per_month_alter_user_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998XXXXXXXXX shaklida bo‘lishi kerak', regex='^\\+998\\d{9}$')]),
        ),
    ]
