# Generated by Django 5.1.4 on 2025-02-24 08:42

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student'), ('applicant', 'Applicant')], default='teacher', max_length=10),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('phone_own', models.CharField(help_text='Masalan: +998901234567', max_length=15, validators=[core.validators.validate_phone_number])),
                ('phone_parents', models.CharField(help_text='Masalan: +998901234567', max_length=15, validators=[core.validators.validate_phone_number])),
                ('study_field', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(choices=[('MWF1', 'Dushanba-Chorshanba-Juma (8:00-10:00)'), ('MWF2', 'Dushanba-Chorshanba-Juma (10:00-12:00)'), ('MWF3', 'Dushanba-Chorshanba-Juma (13:30-15:30)'), ('MWF4', 'Dushanba-Chorshanba-Juma (15:30-17:30)'), ('TTS1', 'Seshanba-Payshanba-Shanba (8:00-10:00)'), ('TTS2', 'Seshanba-Payshanba-Shanba (10:00-12:00)'), ('TTS3', 'Seshanba-Payshanba-Shanba (13:30-15:30)'), ('TTS4', 'Seshanba-Payshanba-Shanba (15:30-17:30)')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
