# Generated by Django 5.1.4 on 2025-04-07 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_role_applicant_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='preferred_time',
            field=models.CharField(choices=[('MWF1', 'Dushanba-Chorshanba-Juma (8:00-10:00)'), ('MWF2', 'Dushanba-Chorshanba-Juma (10:00-12:00)'), ('MWF3', 'Dushanba-Chorshanba-Juma (13:30-15:30)'), ('MWF4', 'Dushanba-Chorshanba-Juma (15:30-17:30)'), ('TTS1', 'Seshanba-Payshanba-Shanba (8:00-10:00)'), ('TTS2', 'Seshanba-Payshanba-Shanba (10:00-12:00)'), ('TTS3', 'Seshanba-Payshanba-Shanba (13:30-15:30)'), ('TTS4', 'Seshanba-Payshanba-Shanba (15:30-17:30)'), ('ALL', 'Dushanba-Shanba')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='study_field',
            field=models.CharField(choices=[('backend', 'Backend (Python)'), ('frontend', 'Frontend'), ('android', 'Mobile (android)'), ('frontend', 'Frontend'), ('computer_science', 'Kompyuter Savodxonligi'), ('graphic', 'Grafik dizayn'), ('3dmax', '3Ds Max')], max_length=50),
        ),
    ]
